#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -xe

source ${OPENSHIFT_HOMEDIR}app-root/runtime/dependencies/python/virtenv/bin/activate

pip install -U pip
pip install -Ue ${OPENSHIFT_REPO_DIR}

mkdir -p ${OPENSHIFT_DATA_DIR}media

pushd ${OPENSHIFT_REPO_DIR}
	if [ -f ${OPENSHIFT_DATA_DIR}sentry ]; then
	    pip install raven
	fi

	bin/install_client_deps.sh

	mkdir -p wsgi/static

	[ -f memopol/local_settings.py ] && rm memopol/local_settings.py
	cp .openshift/local_settings.py memopol/local_settings.py

	./manage.py migrate --noinput
	./manage.py collectstatic --noinput
	./manage.py compress

	ln -sf ${OPENSHIFT_DATA_DIR}media wsgi/static/media
	ln -sf ${OPENSHIFT_DATA_DIR}compress/CACHE wsgi/static/collected/CACHE
popd
