#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -xe

source ${OPENSHIFT_HOMEDIR}app-root/runtime/dependencies/python/virtenv/bin/activate

pip2 install -U pip
pip2 install -Ue ${OPENSHIFT_REPO_DIR}

mkdir -p ${OPENSHIFT_DATA_DIR}media

pushd ${OPENSHIFT_REPO_DIR}
	if [ -f ${OPENSHIFT_DATA_DIR}sentry ]; then
	    pip2 install raven
	fi

	src/memopol/bin/install_client_deps.sh

	mkdir -p wsgi/static

	[ -f src/memopol/local_settings.py ] && rm src/memopol/local_settings.py
	cp .openshift/local_settings.py src/memopol/local_settings.py

	memopol migrate --noinput
	memopol collectstatic --noinput

	ln -sf ${OPENSHIFT_DATA_DIR}media wsgi/static/media
	ln -sf ${OPENSHIFT_DATA_DIR}compress/CACHE wsgi/static/collected/CACHE
popd
